"""empty message

Revision ID: fe3c08e64184
Revises: 
Create Date: 2019-12-14 22:05:54.221581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.point import Point

# revision identifiers, used by Alembic.
revision = 'fe3c08e64184'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircrafts_data', 'aircraft_code',
               existing_type=sa.CHAR(length=3),
               comment=None,
               existing_comment='Aircraft code, IATA')
    op.alter_column('aircrafts_data', 'model',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Aircraft model',
               existing_nullable=False)
    op.alter_column('aircrafts_data', 'rrange',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Maximal flying distance, km',
               existing_nullable=False)
    op.drop_table_comment(
        'aircrafts_data',
        existing_comment='Aircrafts (internal data)',
        schema=None
    )
    op.alter_column('airports_data', 'airport_code',
               existing_type=sa.CHAR(length=3),
               comment=None,
               existing_comment='Airport code')
    op.alter_column('airports_data', 'airport_name',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Airport name',
               existing_nullable=False)
    op.alter_column('airports_data', 'city',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='City',
               existing_nullable=False)
    op.alter_column('airports_data', 'coordinates',
               existing_type=Point(),
               comment=None,
               existing_comment='Airport coordinates (longitude and latitude)',
               existing_nullable=False)
    op.alter_column('airports_data', 'timezone',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Airport time zone',
               existing_nullable=False)
    op.drop_table_comment(
        'airports_data',
        existing_comment='Airports (internal data)',
        schema=None
    )
    op.alter_column('boarding_passes', 'boarding_no',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Boarding pass number',
               existing_nullable=False)
    op.alter_column('boarding_passes', 'flight_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Flight ID')
    op.alter_column('boarding_passes', 'seat_no',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Seat number',
               existing_nullable=False)
    op.alter_column('boarding_passes', 'ticket_no',
               existing_type=sa.CHAR(length=13),
               comment=None,
               existing_comment='Ticket number')
    op.drop_table_comment(
        'boarding_passes',
        existing_comment='Boarding passes',
        schema=None
    )
    op.alter_column('bookings', 'book_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Booking date',
               existing_nullable=False)
    op.alter_column('bookings', 'book_ref',
               existing_type=sa.CHAR(length=6),
               comment=None,
               existing_comment='Booking number')
    op.alter_column('bookings', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Total booking cost',
               existing_nullable=False)
    op.drop_table_comment(
        'bookings',
        existing_comment='Bookings',
        schema=None
    )
    op.alter_column('flights', 'actual_arrival',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Actual arrival time',
               existing_nullable=True)
    op.alter_column('flights', 'actual_departure',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Actual departure time',
               existing_nullable=True)
    op.alter_column('flights', 'aircraft_code',
               existing_type=sa.CHAR(length=3),
               comment=None,
               existing_comment='Aircraft code, IATA',
               existing_nullable=False)
    op.alter_column('flights', 'arrival_airport',
               existing_type=sa.CHAR(length=3),
               comment=None,
               existing_comment='Airport of arrival',
               existing_nullable=False)
    op.alter_column('flights', 'departure_airport',
               existing_type=sa.CHAR(length=3),
               comment=None,
               existing_comment='Airport of departure',
               existing_nullable=False)
    op.alter_column('flights', 'flight_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Flight ID',
               autoincrement=True)
    op.alter_column('flights', 'flight_no',
               existing_type=sa.CHAR(length=6),
               comment=None,
               existing_comment='Flight number',
               existing_nullable=False)
    op.alter_column('flights', 'scheduled_arrival',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Scheduled arrival time',
               existing_nullable=False)
    op.alter_column('flights', 'scheduled_departure',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Scheduled departure time',
               existing_nullable=False)
    op.alter_column('flights', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Flight status',
               existing_nullable=False)
    op.drop_table_comment(
        'flights',
        existing_comment='Flights',
        schema=None
    )
    op.alter_column('seats', 'aircraft_code',
               existing_type=sa.CHAR(length=3),
               comment=None,
               existing_comment='Aircraft code, IATA')
    op.alter_column('seats', 'fare_conditions',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Travel class',
               existing_nullable=False)
    op.alter_column('seats', 'seat_no',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Seat number')
    op.drop_constraint('seats_aircraft_code_fkey', 'seats', type_='foreignkey')
    op.create_foreign_key('boarding_passes_ticket_no_fkey', 'seats', 'aircrafts_data', ['aircraft_code'], ['aircraft_code'])
    op.drop_table_comment(
        'seats',
        existing_comment='Seats',
        schema=None
    )
    op.alter_column('ticket_flights', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Travel cost',
               existing_nullable=False)
    op.alter_column('ticket_flights', 'fare_conditions',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Travel class',
               existing_nullable=False)
    op.alter_column('ticket_flights', 'flight_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Flight ID')
    op.alter_column('ticket_flights', 'ticket_no',
               existing_type=sa.CHAR(length=13),
               comment=None,
               existing_comment='Ticket number')
    op.drop_table_comment(
        'ticket_flights',
        existing_comment='Flight segment',
        schema=None
    )
    op.alter_column('tickets', 'book_ref',
               existing_type=sa.CHAR(length=6),
               comment=None,
               existing_comment='Booking number',
               existing_nullable=False)
    op.alter_column('tickets', 'contact_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Passenger contact information',
               existing_nullable=True)
    op.alter_column('tickets', 'passenger_id',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Passenger ID',
               existing_nullable=False)
    op.alter_column('tickets', 'passenger_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Passenger name',
               existing_nullable=False)
    op.alter_column('tickets', 'ticket_no',
               existing_type=sa.CHAR(length=13),
               comment=None,
               existing_comment='Ticket number')
    op.drop_table_comment(
        'tickets',
        existing_comment='Tickets',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'tickets',
        'Tickets',
        existing_comment=None,
        schema=None
    )
    op.alter_column('tickets', 'ticket_no',
               existing_type=sa.CHAR(length=13),
               comment='Ticket number')
    op.alter_column('tickets', 'passenger_name',
               existing_type=sa.TEXT(),
               comment='Passenger name',
               existing_nullable=False)
    op.alter_column('tickets', 'passenger_id',
               existing_type=sa.VARCHAR(length=20),
               comment='Passenger ID',
               existing_nullable=False)
    op.alter_column('tickets', 'contact_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Passenger contact information',
               existing_nullable=True)
    op.alter_column('tickets', 'book_ref',
               existing_type=sa.CHAR(length=6),
               comment='Booking number',
               existing_nullable=False)
    op.create_table_comment(
        'ticket_flights',
        'Flight segment',
        existing_comment=None,
        schema=None
    )
    op.alter_column('ticket_flights', 'ticket_no',
               existing_type=sa.CHAR(length=13),
               comment='Ticket number')
    op.alter_column('ticket_flights', 'flight_id',
               existing_type=sa.INTEGER(),
               comment='Flight ID')
    op.alter_column('ticket_flights', 'fare_conditions',
               existing_type=sa.VARCHAR(length=10),
               comment='Travel class',
               existing_nullable=False)
    op.alter_column('ticket_flights', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Travel cost',
               existing_nullable=False)
    op.create_table_comment(
        'seats',
        'Seats',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('boarding_passes_ticket_no_fkey', 'seats', type_='foreignkey')
    op.create_foreign_key('seats_aircraft_code_fkey', 'seats', 'aircrafts_data', ['aircraft_code'], ['aircraft_code'], ondelete='CASCADE')
    op.alter_column('seats', 'seat_no',
               existing_type=sa.VARCHAR(length=4),
               comment='Seat number')
    op.alter_column('seats', 'fare_conditions',
               existing_type=sa.VARCHAR(length=10),
               comment='Travel class',
               existing_nullable=False)
    op.alter_column('seats', 'aircraft_code',
               existing_type=sa.CHAR(length=3),
               comment='Aircraft code, IATA')
    op.create_table_comment(
        'flights',
        'Flights',
        existing_comment=None,
        schema=None
    )
    op.alter_column('flights', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Flight status',
               existing_nullable=False)
    op.alter_column('flights', 'scheduled_departure',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Scheduled departure time',
               existing_nullable=False)
    op.alter_column('flights', 'scheduled_arrival',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Scheduled arrival time',
               existing_nullable=False)
    op.alter_column('flights', 'flight_no',
               existing_type=sa.CHAR(length=6),
               comment='Flight number',
               existing_nullable=False)
    op.alter_column('flights', 'flight_id',
               existing_type=sa.INTEGER(),
               comment='Flight ID',
               autoincrement=True)
    op.alter_column('flights', 'departure_airport',
               existing_type=sa.CHAR(length=3),
               comment='Airport of departure',
               existing_nullable=False)
    op.alter_column('flights', 'arrival_airport',
               existing_type=sa.CHAR(length=3),
               comment='Airport of arrival',
               existing_nullable=False)
    op.alter_column('flights', 'aircraft_code',
               existing_type=sa.CHAR(length=3),
               comment='Aircraft code, IATA',
               existing_nullable=False)
    op.alter_column('flights', 'actual_departure',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Actual departure time',
               existing_nullable=True)
    op.alter_column('flights', 'actual_arrival',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Actual arrival time',
               existing_nullable=True)
    op.create_table_comment(
        'bookings',
        'Bookings',
        existing_comment=None,
        schema=None
    )
    op.alter_column('bookings', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Total booking cost',
               existing_nullable=False)
    op.alter_column('bookings', 'book_ref',
               existing_type=sa.CHAR(length=6),
               comment='Booking number')
    op.alter_column('bookings', 'book_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Booking date',
               existing_nullable=False)
    op.create_table_comment(
        'boarding_passes',
        'Boarding passes',
        existing_comment=None,
        schema=None
    )
    op.alter_column('boarding_passes', 'ticket_no',
               existing_type=sa.CHAR(length=13),
               comment='Ticket number')
    op.alter_column('boarding_passes', 'seat_no',
               existing_type=sa.VARCHAR(length=4),
               comment='Seat number',
               existing_nullable=False)
    op.alter_column('boarding_passes', 'flight_id',
               existing_type=sa.INTEGER(),
               comment='Flight ID')
    op.alter_column('boarding_passes', 'boarding_no',
               existing_type=sa.INTEGER(),
               comment='Boarding pass number',
               existing_nullable=False)
    op.create_table_comment(
        'airports_data',
        'Airports (internal data)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('airports_data', 'timezone',
               existing_type=sa.TEXT(),
               comment='Airport time zone',
               existing_nullable=False)
    op.alter_column('airports_data', 'coordinates',
               existing_type=sa.NullType(),
               comment='Airport coordinates (longitude and latitude)',
               existing_nullable=False)
    op.alter_column('airports_data', 'city',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='City',
               existing_nullable=False)
    op.alter_column('airports_data', 'airport_name',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Airport name',
               existing_nullable=False)
    op.alter_column('airports_data', 'airport_code',
               existing_type=sa.CHAR(length=3),
               comment='Airport code')
    op.create_table_comment(
        'aircrafts_data',
        'Aircrafts (internal data)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('aircrafts_data', 'rrange',
               existing_type=sa.INTEGER(),
               comment='Maximal flying distance, km',
               existing_nullable=False)
    op.alter_column('aircrafts_data', 'model',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Aircraft model',
               existing_nullable=False)
    op.alter_column('aircrafts_data', 'aircraft_code',
               existing_type=sa.CHAR(length=3),
               comment='Aircraft code, IATA')
    # ### end Alembic commands ###
